# Site settings
title: String on a Finger
email: jason@jasonhardin.com
author: Jason Hardin
description: "Blog about programming, video games, role-playing games, battlemaps, BBQ and DIY projects."
url: "http://www.jasonhardin.com" # the base hostname & protocol for your site
twitter_username: "@JasonHardin8"
github_username: psychoph
linkedin_username: jasonhardin
steam_id: psychoph
twitch_id: psychoph
psn_id: psychoph03

# Build settings
permalink: pretty
paginate: 5

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
whitelist:
  - jekyll-redirect-from
