# Site settings
title: String on a Finger
email: jason@jasonhardin.com
author: Jason Hardin
description: "Blog about programming, video games, role-playing games, BBQ and DIY projects."
url: "https://newblog.jasonhardin.com" # the base hostname & protocol for your site
twitter_username: "@JasonHardin8"
github_username: psychoph
googleplus_username: JasonHardin
linkedin_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5

gems:
  - jekyll-sitemap